# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4520366f8469dccf110b7fedafea2f52bfb8758f5e4af18a79ea96f7e3248010ed9136075db1d832d645dc73a315207a65c25af2cfe3b84baea2df52d3afb9b0

test:
  secret_key_base: 618b256a110f145a0d088dfc10ff8be885cbd38b55bddffff631cf93b1bf0ba5e2f56e80bb6ac122de6d6002bfdfaf72ee2c73d369abfaa36f45603f2df11001

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
